copy rxnatomarchive from '/home/mlbernauer/HDD/projects/data-rxnorm/rrf/RXNATOMARCHIVE.RRF' with header csv delimiter E'|';
copy rxnconso from '/home/mlbernauer/HDD/projects/data-rxnorm/rrf/RXNCONSO.RRF' with header csv delimiter E'|';
copy rxncuichanges from '/home/mlbernauer/HDD/projects/data-rxnorm/rrf/RXNCUICHANGES.RRF' with header csv delimiter E'|';
copy rxncui from '/home/mlbernauer/HDD/projects/data-rxnorm/rrf/RXNCUI.RRF' with header csv delimiter E'|';
copy rxndoc from '/home/mlbernauer/HDD/projects/data-rxnorm/rrf/RXNDOC.RRF' with header csv delimiter E'|';
copy rxnrel from '/home/mlbernauer/HDD/projects/data-rxnorm/rrf/RXNREL.RRF' with header csv delimiter E'|';
copy rxnsab from '/home/mlbernauer/HDD/projects/data-rxnorm/rrf/RXNSAB.RRF' with header csv delimiter E'|';
copy rxnsat from '/home/mlbernauer/HDD/projects/data-rxnorm/rrf/RXNSAT.RRF' with header csv delimiter E'|';
copy rxnsty from '/home/mlbernauer/HDD/projects/data-rxnorm/rrf/RXNSTY.RRF' with header csv delimiter E'|';
